### ISSUE TITLE
Add the ability to load niftis

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox-py#13]
Convert the current load_niftis function from shimming-toolbox repo to this repo.

The load_niftis function allows to load an entire acquisition instead of only single nifti files at a time. (The original function also allowed to select the acquisition from a list depending on the input)

For example:
The output of dcm2bids for the [dicom_unsorted](https://github.com/shimming-toolbox/data-testing/tree/master/dicom_unsorted) is 6 different phase files organized in `./fmap` called `./fmap/sub-test_phaseX.nii`. The goal of the function is to call `phase = load_niftis/load_acquistion('./fmap')` instead of calling 6 times `nibabel.load()` then stitching them in the required format for our API which we agreed was (x, y, z, echoes, volumes). This example is for different echoes but the function should accommodate different volumes through time as well.

**Comment by jcohenadad** [comment]
@gab-berest what working branch are you for this issue?

**Comment by gab-berest** [comment]
> 
> 
> @gab-berest what working branch are you for this issue?

I'm working in the branch gb/load_nifti. I have to talk to @gaspardcereza to check for the function read_nii since I use it and there was some issue with how it was loaded.

**Comment by jcohenadad** [comment]
> I have to talk to @gaspardcereza to check for the function read_nii since I use it and there was some issue with how it was loaded.

can we rather have the discussion on this github thread (or another more appropriate thread)-- so that the whole team is on the same page-- thanks

**Comment by gab-berest** [comment]
@jcohenadad Is there available Nifti data to download for unittesting? I created dummy data with nibabel for now, but it could be easier if we could download Nifti data directly.

**Comment by po09i** [comment]
Yes, you can use the [download data](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/shimmingtoolbox/cli/download_data.py) CLI on master.

**Comment by jcohenadad** [comment]
> @jcohenadad Is there available Nifti data to download for unittesting? I created dummy data with nibabel for now, but it could be easier if we could download Nifti data directly.

https://github.com/shimming-toolbox/data-testing
also see https://github.com/shimming-toolbox/shimming-toolbox-py/pull/15 which includes data download in CI

**Comment by jcohenadad** [comment]
@gab-berest @po09i i'm not convinced about the relevance of this issue-- the body says: "Convert the current load_niftis function from shimming-toolbox repo to this repo"

could you please elaborate about what features are needed exactly? `nibabel.load()` already reads nifti, so why do we need a dedicated API?

**Comment by po09i** [comment]
I updated the description, the name of the function could be updated to something more descriptive like load_acquisition.

**Comment by jcohenadad** [comment]
> The load_niftis function allows to load an entire acquisition instead of only single nifti files at a time. (The original function also allowed to select the acquisition from a list depending on the input)

what do you mean by "entire acquisition"? a collection of multiple MRI volumes acquired during a single session? what would be the expected output of such function? or the specific actions to the images (e.g. triage depending on type?). More context/info/description is needed to be able to design the function-- thanks

**Comment by po09i** [comment]
I think an example is better suited for this. The output of dcm2bids for the [dicom_unsorted](https://github.com/shimming-toolbox/data-testing/tree/master/dicom_unsorted) is 6 different phase images in a folder called `./fmap/sub-test_phaseX.nii`. The goal of the function is to call `phase = load_niftis/load_acquistion('./fmap')` instead of calling 6 times `nibabel.load()` then stitching them in the required format for our API which we agreed was (x, y, z, echoes, volumes). This example is for different echoes but the function should accommodate different volumes through time as well. Hopefully this is clearer.

**Comment by gab-berest** [comment]
> 
> 
> > The load_niftis function allows to load an entire acquisition instead of only single nifti files at a time. (The original function also allowed to select the acquisition from a list depending on the input)
> 
> what do you mean by "entire acquisition"? a collection of multiple MRI volumes acquired during a single session? what would be the expected output of such function? or the specific actions to the images (e.g. triage depending on type?). More context/info/description is needed to be able to design the function-- thanks

Form what I understand, it is exactly what @po09i  said. It will provide a function to load multiple .nii files in one go instead of calling multiple times the nibabel package. I only did the different echoes for now. I'll update further when I've implemented for multiple volume as well.

**Comment by gab-berest** [comment]
@po09i  to correctly understand, how is the nii data different if we have volume (since I don't have data with different volumes to test this)? Are all the volumes stored in the same .nii file for each echo?

**Comment by po09i** [comment]
I'm not entirely sure. You could play with some [OSF data](https://osf.io/7d2j5/) we have (acdc108 was a time series from what I remember) to figure it out.

**Comment by jcohenadad** [comment]
> I think an example is better suited for this. The output of dcm2bids for the dicom_unsorted is 6 different phase images in a folder called ./fmap/sub-test_phaseX.nii. The goal of the function is to call phase = load_niftis/load_acquistion('./fmap') instead of calling 6 times nibabel.load() then stitching them in the required format for our API which we agreed was (x, y, z, echoes, volumes). This example is for different echoes but the function should accommodate different volumes through time as well. Hopefully this is clearer.

much clearer! thanks. Yes, i agree with feature will be useful. Could you pls update the body of the issue so it clarifies for the whole team. Also please add example scenario so we can anticipate what features will be needed for this API. Examples from typical scenario:

````python
# extract data into BIDS dataset
convert_dicom_to_bids(path_dicom, path_nifti_dataset, subject='sub-01')
# assign path to subject for this experiment
path_nifti_sub = os.path.join(path_nifti, 'sub-01')
# load phase for computing fieldmap
# the 'modality' will automatically indicate to look into the folder fmap/ as per BIDS convention
# the 'type' could be 'phase' or 'mag' and will be able to select the appropriate nifti files
# note: in case multiple phase/mag fieldmaps were acquired (e.g. re-acquisitions), select the latest one by default. Otherwise, we need another field to select the acquisition (e.g., ID?)
phase = load_nifti(path_nifti_sub, modality='fmap', type='phase')
# fetch anatomical T2* data for segmentation 
...
````

the scenario above illustrates the importance of anticipating how the proposed function will be used, by describing extensively multiple possible scenarios, so that when the function is being developed we can solve the anticipated scenario, otherwise we will end up patching the function iteratively, which will take longer than if it was well thought from the beginning. A collateral, and much needed benefits of describing the scenario, is that it gives the opportunity for the whole team to brainstorm on the development, and bring ideas/feedback _before_ the function is implemented.
