### ISSUE TITLE
Agree on docstrings convension

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#16]
how about we follow those guidelines: https://ivadomed.org/en/latest/contributing.html#documentation-and-docstrings?

with the Google style docstrings.

**Comment by po09i** [comment]
Yes, I like the google style a lot more than Restructured Text style. I'm using PyCharm as an IDE, I found this [page](https://www.jetbrains.com/help/pycharm/settings-tools-python-integrated-tools.html) to easily change the style to auto-document the structure of the docstring when using PyCharm.

**Comment by gab-berest** [comment]
Yes, it is easily understandable and parsable for documentation.

**Comment by po09i** [comment]
We went for [google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). This can be closed
