### ISSUE TITLE
Bundle prelude as a dependency to run on Travis

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox-py#23]
To test prelude on Travis, prelude needs to be bundled as a dependency so that Travis can run prelude.

**Comment by jcohenadad** [comment]
@kousu what do you think we should do? We only need one binary from FSL. They have a [neurodebian installer](http://neuro.debian.net/pkgs/fsl-complete.html) but it is still "heavy" to run at each test. 

Anticipating that we will need other 3rd party binaries for testing, should we start a repos with all the dependencies (e.g. prelude) for a specific OS that is being used by Travis, and download that repos when running Travis?
