### ISSUE TITLE
Install dcm2niix for testing suite

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#27]
Testing suite will required [dcm2niix](https://github.com/rordenlab/dcm2niix), which is a dependency of [dcm2bids](https://github.com/cbedetti/Dcm2Bids).

According to the doc, there are various ways to install it, including:
- conda: `conda install -c conda-forge dcm2niix`  (for Linux, MacOS or Windows).
- [pre-built packages](https://github.com/rordenlab/dcm2niix/releases)

Question: which one should we go for? i vote for conda

**Comment by kousu** [comment]
Or you can use the pre-built package that [debian makes](https://packages.debian.org/buster/dcm2niix): #28. That avoids adding another layer of environment.
