### ISSUE TITLE
Controlling which version of dcm2niix is installed

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox-py#42]
# Context
Has mentionned [here](https://github.com/shimming-toolbox/shimming-toolbox-py/pull/18#issuecomment-665818569), Travis downloads dcm2niix `v1.0.20171215` instead of `v1.0.20200331` which is the last release.
It might be the cause of the test failure when pushing #18. 

Currently, dmc2niix is installed by running `sudo apt-get install -y dcm2niix` in [.travis.yml](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/.travis.yml).

**Comment by gaspardcereza** [comment]
@kousu have you ever faced a similar problem ?

**Comment by jcohenadad** [comment]
@gaspardcereza i changed the title of this issue-- the fundamental problem is that we want to control which version of dcm2niix is installed, not only on travis, but also on the user side.

they have a [conda install](https://anaconda.org/conda-forge/dcm2niix) but do we want to enforce the use of conda? @kousu 

should we check the version and display an error if the version does not match the version we hard-code somewhere in a test_dcm2niix function? that might require some maintenance

**Comment by jcohenadad** [comment]
in addition to @kousu's suggestions https://github.com/shimming-toolbox/shimming-toolbox-py/pull/18#issuecomment-665896373, there is also the possibility to package dcm2niix binaries as part of a dependent repository (e.g. https://github.com/shimming-toolbox/binaries)

**Comment by kousu** [comment]
(from https://github.com/shimming-toolbox/shimming-toolbox-py/pull/18#issuecomment-665896373) 

This CI error is telling you is that the software is not compatible with the version of dcm2niix that many of your users will have access to. That is useful information, as annoying as it seems right now. You should try to get it working with both versions.

If you have docker installed, you can do `docker run --rm -it ubuntu:bionic` to get an Linux environment, and in there you can copy the CI script manually until you hit the error, and then try to debug from there. It's likely there's an easy workaround: `if $(dcm2niix --version) < 2020 { then call dcm2niix differently }`. This pattern is in a lot of python libraries, and it is reliable and sound.

`conda` is an alternative, but if we do that we're not longer cross-platform, the platform becomes conda. That's okay, but I think we need to go into it with eyes-wide-open that that's the bargain we're striking.

**Comment by jcohenadad** [comment]
@kousu how about https://github.com/shimming-toolbox/shimming-toolbox-py/issues/42#issuecomment-665901973?

**Comment by jcohenadad** [comment]
from @gab-berest in https://github.com/shimming-toolbox/shimming-toolbox-py/pull/18#issuecomment-665954269
> Normally for a package, it should be linked to a specific version of the dependencies (as the setup file requires). If we want to use at least the version v1.0.20200331, I would build the OS dependencies instead so it will be easier to debug since the dcm2niix version will be known and compatible. A make file can easily build these binaries from source and install them on the device.

if users don't have the "proper" os, they will bump into the same problem. so i would not solve this issue only for travis, but for travis+our users. meaning: i'm inclined to "bundle" dcm2niix with shimming-toolbox. https://github.com/shimming-toolbox/shimming-toolbox-py/issues/42#issuecomment-665901973 is one (non-elegant bug pragmatic) solution. i'm open to other solutions

**Comment by kousu** [comment]
I think bundling (jargon: "vendoring") is a lot of work on our end and I'd like to avoid it. `dcm2niix` is already packaged! I'm sure we can make it work with that version.

**Comment by kousu** [comment]
So, I traced the glitch.

<details>

The older version of dcm2niix produces

```
ci@fc4d04b3b1d3:~/shimming-toolbox-py$ ls /tmp/dicom_to_nifti/nifti/tmp_dcm2bids/sub-test/
006_testing_data_a_gre_DYNshim_20191101153345.json       007_testing_data_a_gre_DYNshim_20191101153345_e1.json
006_testing_data_a_gre_DYNshim_20191101153345.nii.gz     007_testing_data_a_gre_DYNshim_20191101153345_e1.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e2.json    007_testing_data_a_gre_DYNshim_20191101153345_e2.json
006_testing_data_a_gre_DYNshim_20191101153345_e2.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e2.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e3.json    007_testing_data_a_gre_DYNshim_20191101153345_e3.json
006_testing_data_a_gre_DYNshim_20191101153345_e3.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e3.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e4.json    007_testing_data_a_gre_DYNshim_20191101153345_e4.json
006_testing_data_a_gre_DYNshim_20191101153345_e4.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e4.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e5.json    007_testing_data_a_gre_DYNshim_20191101153345_e5.json
006_testing_data_a_gre_DYNshim_20191101153345_e5.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e5.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e6.json    007_testing_data_a_gre_DYNshim_20191101153345_e6.json
006_testing_data_a_gre_DYNshim_20191101153345_e6.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e6.nii.gz
```

the newer version

```
[ci@b9868a71bbf6 shimming-toolbox-py]$ ls /tmp/dicom_to_nifti/nifti/tmp_dcm2bids/sub-test/
006_testing_data_a_gre_DYNshim_20191101153345_e1.json    007_testing_data_a_gre_DYNshim_20191101153345_e1_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e1.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e1_ph.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e2.json    007_testing_data_a_gre_DYNshim_20191101153345_e2_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e2.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e2_ph.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e3.json    007_testing_data_a_gre_DYNshim_20191101153345_e3_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e3.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e3_ph.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e4.json    007_testing_data_a_gre_DYNshim_20191101153345_e4_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e4.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e4_ph.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e5.json    007_testing_data_a_gre_DYNshim_20191101153345_e5_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e5.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e5_ph.nii.gz
006_testing_data_a_gre_DYNshim_20191101153345_e6.json    007_testing_data_a_gre_DYNshim_20191101153345_e6_ph.json
006_testing_data_a_gre_DYNshim_20191101153345_e6.nii.gz  007_testing_data_a_gre_DYNshim_20191101153345_e6_ph.nii.gz
```

</details>

Two problems:

1. the older version doesn't put the "_e1" tag on the first file (and the .json file is missing `"EchoNumber": 1`).
    - I tracked this change down to https://github.com/rordenlab/dcm2niix/commit/4ae1aa87571f2fb4f9f78f0e9f8b4ba1fed132d1; an API change thrown into an unrelated commit?
2. the older version doesn't put the "_ph" tag on the phase files (and the .json files read `"ImageType": ["ORIGINAL", "PRIMARY", "P", "ND"]` instead of `"ImageType": ["ORIGINAL", "PRIMARY", "P", "ND", "PHASE"]` as in the newer version)
    - this is only a problem because we don't know how to (can't?) tell dcm2bids "only match `ImageType[2] == "P"`" but instead need to express the filter in config/dcm2bids.json as `"ImageType": ["*", "*", "P", "*", "*"]`, which breaks when the length of that list changes. Bother!

Tracing this has convinced me that trying to be backwards compatible is going to be too hard. I was really hoping it wouldn't be so tricky. I think if dcm2bids was more flexible about specifying filters (or maybe it already is and we just don't understand it yet) then 2. would be a non-issue, but 1. is a fiddly fiddly bugfix because the old dcm2niix is throwing away the `isMultiEcho` bit and there's no way to recover that.

Luckily, I also discovered while doing all this that dcm2niix [provides binaries](https://github.com/rordenlab/dcm2niix/releases). So let's just package those. Actually, we don't need to package them, we can pull them straight from Github.

**Comment by jcohenadad** [comment]
> Luckily, I also discovered while doing all this that dcm2niix [provides binaries](https://github.com/rordenlab/dcm2niix/releases). So let's just package those. Actually, we don't need to package them, we can pull them straight from Github.

that's what i meant in https://github.com/shimming-toolbox/shimming-toolbox-py/issues/42#issuecomment-665901973, but indeed, no need to package them.

**Comment by gaspardcereza** [comment]
> Luckily, I also discovered while doing all this that dcm2niix [provides binaries](https://github.com/rordenlab/dcm2niix/releases). So let's just package those. Actually, we don't need to package them, we can pull them straight from Github.

@kousu Is there a way to tell Travis to directly download these binaries from dcm2niix's GitHub in the `.travis.yml` file ?

**Comment by kousu** [comment]
@gaspardcereza yep! Please review https://github.com/shimming-toolbox/shimming-toolbox-py/pull/43/files. It will show you how I accomplished that.
