### ISSUE TITLE
Fix docstring in masking module

### ISSUE THREAD

**Issue by jidicula** [shimming-toolbox/shimming-toolbox-py#71]
Sphinx build is raising a build warning:

```
WARNING: autodoc: failed to import module 'shape' from module 'shimmingtoolbox.masking'; the following exception was raised:
No module named 'shimmingtoolbox.masking.shape'
```

**Comment by jcohenadad** [comment]
i vaguely remember @po09i adding an ‘s’ for the API name: shapes

**Comment by jidicula** [comment]
> i vaguely remember @po09i adding an ‘s’ for the API name: shapes

Yep, I just caught that in my fix – PR incoming!

**Comment by po09i** [comment]
@jidicula Can this be closed?

**Comment by jidicula** [comment]
> @jidicula Can this be closed?

Yes, I'll close it!
