### ISSUE TITLE
Missing tsv and dataset_description.json from dicom_to_nifti

### ISSUE THREAD

**Issue by gab-berest** [shimming-toolbox/shimming-toolbox-py#77]
When using dicom_to_nifti function, most of the dataset information files in json or tsv format are missing. dcm2bids should be correctly configured to generate at least the template files without information.

**Comment by gab-berest** [comment]
Missing function calls to help create those files:
`dcm2bids_scaffold` to create all the sourcedata hierarchy (dicom files should be copied in sourcedata folder)
`dcm2bids_helper -d sourcedata/path_to_dicom_files` to create temporary nifti files reflecting dicom hierarchy
`dcm2bids -d sourcedata/DICOM_PATH -p SUBJECT_NUMBER -o OUTPUT_PATH -c CONFIG_PATH`

**Comment by gaspardcereza** [comment]
Indeed these different steps have been removed and they shouldn't. It must have been a  mistake we did during our coding sessions [(see this commit)](https://github.com/shimming-toolbox/shimming-toolbox-py/commit/73893dea2318d19bbfac77231cef87ee0a4ebb3d). 
The need for these functions is precisely mentioned [here](https://github.com/cbedetti/Dcm2Bids).

**Comment by jcohenadad** [comment]
> Indeed these different steps have been removed and they shouldn't. It must have been a mistake we did during our coding sessions [(see this commit)](https://github.com/shimming-toolbox/shimming-toolbox-py/commit/73893dea2318d19bbfac77231cef87ee0a4ebb3d).
> The need for these functions is precisely mentioned [here](https://github.com/cbedetti/Dcm2Bids).

my mistake, sorry 😬

**Comment by gab-berest** [comment]
> 
> 
> Indeed these different steps have been removed and they shouldn't. It must have been a mistake we did during our coding sessions [(see this commit)](https://github.com/shimming-toolbox/shimming-toolbox-py/commit/73893dea2318d19bbfac77231cef87ee0a4ebb3d).
> The need for these functions is precisely mentioned [here](https://github.com/cbedetti/Dcm2Bids).

So we should revert to this commit?

**Comment by gaspardcereza** [comment]
> > Indeed these different steps have been removed and they shouldn't. It must have been a mistake we did during our coding sessions [(see this commit)](https://github.com/shimming-toolbox/shimming-toolbox-py/commit/73893dea2318d19bbfac77231cef87ee0a4ebb3d).
> > The need for these functions is precisely mentioned [here](https://github.com/cbedetti/Dcm2Bids).
> 
> So we should revert to this commit?

If think we could find some compromise between the cleaned up code where the functions are missing and the original commit that may not be optimal. @jcohenadad what do you think of it ?

**Comment by jcohenadad** [comment]
> > Indeed these different steps have been removed and they shouldn't. It must have been a mistake we did during our coding sessions [(see this commit)](https://github.com/shimming-toolbox/shimming-toolbox-py/commit/73893dea2318d19bbfac77231cef87ee0a4ebb3d).
> > The need for these functions is precisely mentioned [here](https://github.com/cbedetti/Dcm2Bids).
> 
> So we should revert to this commit or another one?

hum... not sure about that... we need to look at the implications... not all the code might be necessary, etc.

**Comment by jcohenadad** [comment]
> If think we could find some compromise between the cleaned up code where the functions are missing and the original commit that may not be optimal. @jcohenadad what do you think of it ?

yes that's exactly what i had in mind

**Comment by gab-berest** [comment]
I'll create a new branch to resolve this issue and have the discussion in there. I know that the scaffold and helper calls are mandatory to make all the necessary files. the config file is not necessary for me, but we'll see.
