### ISSUE TITLE
Consider changing coils object for a class

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#80]
As of a1bb94318a9559d04857f1c7541e1c340bc22ff1, coil object generated by `shimmingtoolbox.coils.XXX` is a np.array: `[nx, ny, nz, coeffs]`. The problem with this format, is that we are missing relevant information, such as:
- units 
- labels (eg: 'Z', 'XY', etc.)

A suggestion would be to make `coil` a Class which would include the properties above

Related to https://github.com/shimming-toolbox/shimming-toolbox-py/issues/21

**Comment by po09i** [comment]
Duplicate of #79, this can be closed
