### ISSUE TITLE
Save arbitrary non-spherical harmonics coil profile for testing purpose

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#82]
Currently, the optimization testing suite is using spherical harmonics coil profile, which can be generated on the fly (fast). We now have another way to generate arbitrary profiles from Biot-Savart law (https://github.com/shimming-toolbox/shimming-toolbox-py/pull/73) so it would be nice to add it to our testing suite.

Given that the generation of these profiles can be slow, we could consider saving a numpy array as a file and include it in our testing dataset.

**Comment by po09i** [comment]
As discussed in an internal meeting, the biot-savart numpy array can be generated on the fly and is not that long. This can be closed.
