### ISSUE TITLE
Update testing data

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#84]
The current testing data release (r20200713) is fairly old and does not include the latest additions.

We should consider updating the link on the `st_download_data` CLI.

Things to check before updating the link: 
- [ ] Make sure the testing data contain examples for realtime z-shimming scenario

**Comment by po09i** [comment]
@evaalonsoortiz confirmed that [realtime_zshimming_data](https://github.com/shimming-toolbox/data-testing/tree/master/realtime_zshimming_data) contains the necessary data.

**Comment by jcohenadad** [comment]
i’ve noticed redundancy in this folder (eg: both dicoms and nifti, which is unnecessary)

**Comment by po09i** [comment]
Are you referring to this [folder](https://github.com/shimming-toolbox/data-testing/tree/master/sub-fieldmap/fmap)? If so then the idea was to be able to unwrap them using travis without any processing from dicom_to_nifti. Otherwise there are only dicoms in the data_testing repo.

**Comment by jcohenadad** [comment]
i was talking about https://github.com/shimming-toolbox/data-testing/tree/master/realtime_zshimming_data, but you’re right, it’s only dcm. I had nii on my local station but it was due to local conversion. so it’s all good 👌
