### ISSUE TITLE
Installation issue with zsh

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#96]
the following command does not run on zsh
````
pip install -e .[testing]
zsh: no matches found: .[testing]
````

@lcbMGH will fill up with more info

**Comment by lcbMGH** [comment]
Command requires escaping brackets: 'pip install -e .\[testing\]

**Comment by jcohenadad** [comment]
> Does this require documentation updates?

either that, or simply include pytest in the default install. The pros (remove maintenance/confusion/doc reading, enables user to run pytest) outweigh the cons (un-clean).  Plus: package is very small.

**Comment by po09i** [comment]
zsh users need to add "" so this is the command to use: `pip install -e ".[testing,docs]"` to make it work, this is documented in the installation procedure on the website. I'm fairly positive that this is compatible with bash and other shells (need the confirmation).

Pro: separates what users need and what developers need.

**Comment by jcohenadad** [comment]
@lcbMGH @gaspardcereza can you please confirm that `pip install -e ".[testing,docs]"` works for you?

**Comment by lcbMGH** [comment]
> @lcbMGH @gaspardcereza can you please confirm that `pip install -e ".[testing,docs]"` works for you? (ie: you are able to run pytest afterwards)

Yes, it does work, as does `pip install -e .\[testing,docs\]`. The pros argument is valid, although I'd argue that the tests are useful to run on install to make sure everything is installed correctly.

**Comment by jcohenadad** [comment]
We agreed in an internal meeting to keep testing in the default install, but have docs as an optional package.
